### ISSUE TITLE
is it possiblie to add a 'restartDriver' command ?

### ISSUE THREAD

**Issue by krisdaniels** [OpenZWave/node-red-contrib-openzwave#3]
This is more of a feature request than an issue, but is it possible to 
add a 'restartDriver' command to restart the connection attempts instead of doing a process.exit() ?  This way I can handle the reconnect cycle from within node-red instead of having it restart the entire process.

**Comment by ekarak** [comment]
I'm planning to add all these missing  management functions... stay tuned.
Same bat time, same bat github.. :)
Στις 17 Μαϊ 2015 3:09 μ.μ., ο χρήστης "Kris Daniels" <
notifications@github.com> έγραψε:

**Comment by ekarak** [comment]
stay tuned, feature is on its way! I've refactored the code in the underlying openzwave engine (check out https://github.com/OpenZWave/node-openzwave-shared ) to allow for easy addition of new OZW commands, so please bear with me, I hope to have it ready in a few days...

**Comment by ekarak** [comment]
I've just committed some preliminary work I've made to add management functions to node-openzwave-shared.
BTW, the concept here is that the hidden zwave-config node never needs to restart when doing changes; (as all NR flow edits should be fast). However, what I _assume_ you're talking about is eg. unplugging the USB stick from a running NR server eg to pair with new devices?

**Comment by krisdaniels** [comment]
That was exactly what I had in mind.  Also unplugging it to use it on another machine, but that node red is able to recover the connection after a message is send, when it is plugged back in without continuously needing to retry the connection to the tty.

**Comment by ekarak** [comment]
Hey Kris,
I've done some extensive work in exposing the vast majority of API calls in Manager.h into Node.js. Since I don't own a second zwave stick (the first and only one is in production use) I find it difficult to test and experiment this. Can you please check out the latest and greatest https://github.com/OpenZWave/node-openzwave-shared and try it out?
I'm interested in defining what do you actually want to do.
- Do you need to be able to pull out your Aeon labs ZStick so as to pair it with new devices and then plug it back in? 
- Or are you referring to what happens when you edit your Node-Red flows? I've already put some effort in making the zwave configuration node resilient to flow redeployments so that we don't have to reinitialise OZW (which is a lengthy process), is this not working for you?

**Comment by ekarak** [comment]
closing
